baseURL = "http://www.vaibhavgupta.me/"
languageCode = "en-us"
title = "Vaibhav Gupta"
theme = "minimal"
publishDir = "docs"

[params]
    author = "Vaibhav Gupta"
    description = "Personal Log"
    githubUsername = "vaibhavguptaIITD"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:vaibhavgupta007@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/vaibhavguptaIITD/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/vaibhavgupta007/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/vaibhavguptaiitd/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.facebook.com/vaibhavgupta.iitd/"
    name = "facebook"
    weight = 5
